/**
 * Error codes for the Rasika.life application
 * Format: [DOMAIN]_[ERROR_TYPE]
 */

export const ErrorCode = {
  // General errors
  GENERAL_INTERNAL_ERROR: 'GENERAL_INTERNAL_ERROR',
  GENERAL_VALIDATION_ERROR: 'GENERAL_VALIDATION_ERROR',
  GENERAL_NOT_FOUND: 'GENERAL_NOT_FOUND',
  GENERAL_ALREADY_EXISTS: 'GENERAL_ALREADY_EXISTS',
  GENERAL_UNAUTHORIZED: 'GENERAL_UNAUTHORIZED',
  GENERAL_FORBIDDEN: 'GENERAL_FORBIDDEN',
  
  // Database errors
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_QUERY_ERROR: 'DB_QUERY_ERROR',
  DB_WRITE_ERROR: 'DB_WRITE_ERROR',
  DB_DELETE_ERROR: 'DB_DELETE_ERROR',
  
  // User domain errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INVALID_CREDENTIALS: 'USER_INVALID_CREDENTIALS',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_USERNAME_ALREADY_EXISTS: 'USER_USERNAME_ALREADY_EXISTS',
  USER_INSUFFICIENT_KARMA: 'USER_INSUFFICIENT_KARMA',
  
  // Artist domain errors
  ARTIST_NOT_FOUND: 'ARTIST_NOT_FOUND',
  ARTIST_ALREADY_EXISTS: 'ARTIST_ALREADY_EXISTS',
  ARTIST_VERIFICATION_FAILED: 'ARTIST_VERIFICATION_FAILED',
  ARTIST_INVALID_MANAGER: 'ARTIST_INVALID_MANAGER',
  
  // Composition domain errors
  COMPOSITION_NOT_FOUND: 'COMPOSITION_NOT_FOUND',
  COMPOSITION_ALREADY_EXISTS: 'COMPOSITION_ALREADY_EXISTS',
  COMPOSITION_VERSION_CONFLICT: 'COMPOSITION_VERSION_CONFLICT',
  
  // Raga domain errors
  RAGA_NOT_FOUND: 'RAGA_NOT_FOUND',
  RAGA_ALREADY_EXISTS: 'RAGA_ALREADY_EXISTS',
  RAGA_VERSION_CONFLICT: 'RAGA_VERSION_CONFLICT',
  
  // Tala domain errors
  TALA_NOT_FOUND: 'TALA_NOT_FOUND',
  TALA_ALREADY_EXISTS: 'TALA_ALREADY_EXISTS',
  TALA_VERSION_CONFLICT: 'TALA_VERSION_CONFLICT',
  
  // Event domain errors
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_ALREADY_EXISTS: 'EVENT_ALREADY_EXISTS',
  EVENT_DATE_CONFLICT: 'EVENT_DATE_CONFLICT',
  EVENT_INVALID_DATE_RANGE: 'EVENT_INVALID_DATE_RANGE',
  
  // Venue domain errors
  VENUE_NOT_FOUND: 'VENUE_NOT_FOUND',
  VENUE_ALREADY_EXISTS: 'VENUE_ALREADY_EXISTS',
  
  // Forum domain errors
  THREAD_NOT_FOUND: 'THREAD_NOT_FOUND',
  REPLY_NOT_FOUND: 'REPLY_NOT_FOUND',
  THREAD_CLOSED: 'THREAD_CLOSED',
  
  // WhatsApp domain errors
  WHATSAPP_VERIFICATION_FAILED: 'WHATSAPP_VERIFICATION_FAILED',
  WHATSAPP_MESSAGE_FAILED: 'WHATSAPP_MESSAGE_FAILED',
  WHATSAPP_FLOW_EXPIRED: 'WHATSAPP_FLOW_EXPIRED',
  
  // Collection domain errors
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',
  COLLECTION_ACCESS_DENIED: 'COLLECTION_ACCESS_DENIED',
  
  // Karma domain errors
  KARMA_INSUFFICIENT: 'KARMA_INSUFFICIENT',
  KARMA_ACTION_DENIED: 'KARMA_ACTION_DENIED',
  
  // Notification domain errors
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',
  NOTIFICATION_TEMPLATE_NOT_FOUND: 'NOTIFICATION_TEMPLATE_NOT_FOUND',
  
  // Payment domain errors
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  PAYMENT_INVALID_AMOUNT: 'PAYMENT_INVALID_AMOUNT',
  REFUND_FAILED: 'REFUND_FAILED',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE'
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];