packages:
  - packages/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - aws-sdk
  - esbuild
  - protobufjs
  - sharp
  - vite-plugin-node-externals

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
