/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "RasikaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "RasikaTRPC": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "RasikaTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RasikaWeb": {
      "type": "sst.aws.React"
      "url": string
    }
    "SearchIndexBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SearchReindex": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}